# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import lazypage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True)),
                ('value', models.BinaryField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=lazypage.models.generate_expired_at)),
            ],
        ),
    ]
